export const ITEMS_LOAD_SUCCESS = 'ITEMS_LOAD_SUCCESS';
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_ACTION_FAILED = 'ITEM_ACTION_FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';
